sonar.projectKey=ai-processing-service
sonar.projectName=AI Processing Service Hackathon
sonar.sources=app
sonar.tests=tests
sonar.language=php
sonar.sourceEncoding=UTF-8
sonar.php.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=app/Providers/**,app/Exceptions/**,app/Console/Kernel.php,app/Http/Middleware/**,app/Models/User.php
