sonar.projectKey=api-gateway
sonar.projectName=API Gateway Hackathon
sonar.sources=app
sonar.tests=tests
sonar.language=php
sonar.sourceEncoding=UTF-8
sonar.php.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=app/Providers/**,app/Exceptions/**,app/Console/**,app/Http/Middleware/**,app/Models/User.php,app/Infrastructure/Adapters/RabbitMQDiagramAdapter.php
